"""create support request table

Revision ID: 2564f4e77e2e
Revises: 7c547ee975fa
Create Date: 2026-07-22 15:00:02.120947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2564f4e77e2e'
down_revision: Union[str, Sequence[str], None] = '7c547ee975fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support_requests',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('assigned_user_id', sa.UUID(), nullable=True),
    sa.Column('request_number', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'IN_PROGRESS', 'WAITING_FOR_CONTACT', 'RESOLVED', 'CLOSED', name='support_request_status'), server_default='NEW', nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='support_request_priority'), server_default='MEDIUM', nullable=False),
    sa.Column('channel', sa.Enum('WEB_FORM', 'API', 'MANUAL', name='support_request_channel'), nullable=False),
    sa.Column('external_reference', sa.String(length=255), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'request_number', name='uq_support_requests_organization_request_number')
    )
    op.create_index(op.f('ix_support_requests_assigned_user_id'), 'support_requests', ['assigned_user_id'], unique=False)
    op.create_index(op.f('ix_support_requests_contact_id'), 'support_requests', ['contact_id'], unique=False)
    op.create_index(op.f('ix_support_requests_organization_id'), 'support_requests', ['organization_id'], unique=False)
    op.create_index(op.f('ix_support_requests_priority'), 'support_requests', ['priority'], unique=False)
    op.create_index(op.f('ix_support_requests_status'), 'support_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_support_requests_status'), table_name='support_requests')
    op.drop_index(op.f('ix_support_requests_priority'), table_name='support_requests')
    op.drop_index(op.f('ix_support_requests_organization_id'), table_name='support_requests')
    op.drop_index(op.f('ix_support_requests_contact_id'), table_name='support_requests')
    op.drop_index(op.f('ix_support_requests_assigned_user_id'), table_name='support_requests')
    op.drop_table('support_requests')
    # ### end Alembic commands ###
