"""create support request access tokens table

Revision ID: 2efb75584c86
Revises: 6c95f31f9d0a
Create Date: 2026-07-22 15:16:27.696184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2efb75584c86'
down_revision: Union[str, Sequence[str], None] = '6c95f31f9d0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support_request_access_tokens',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('support_request_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['support_request_id'], ['support_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_request_access_tokens_contact_id'), 'support_request_access_tokens', ['contact_id'], unique=False)
    op.create_index(op.f('ix_support_request_access_tokens_expires_at'), 'support_request_access_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_support_request_access_tokens_organization_id'), 'support_request_access_tokens', ['organization_id'], unique=False)
    op.create_index(op.f('ix_support_request_access_tokens_support_request_id'), 'support_request_access_tokens', ['support_request_id'], unique=False)
    op.create_index(op.f('ix_support_request_access_tokens_token_hash'), 'support_request_access_tokens', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_support_request_access_tokens_token_hash'), table_name='support_request_access_tokens')
    op.drop_index(op.f('ix_support_request_access_tokens_support_request_id'), table_name='support_request_access_tokens')
    op.drop_index(op.f('ix_support_request_access_tokens_organization_id'), table_name='support_request_access_tokens')
    op.drop_index(op.f('ix_support_request_access_tokens_expires_at'), table_name='support_request_access_tokens')
    op.drop_index(op.f('ix_support_request_access_tokens_contact_id'), table_name='support_request_access_tokens')
    op.drop_table('support_request_access_tokens')
    # ### end Alembic commands ###
